### ISSUE TITLE
self-referencing

### ISSUE THREAD

**Issue by fjod** [dotnet/EntityFramework.Docs.ru-ru#26]
please add examples for self-referencing relationship!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Связи — EF Core](https://docs.microsoft.com/ru-ru/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#feedback)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @fjod
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/EntityFramework.Docs #2321](https://github.com/dotnet/EntityFramework.Docs/issues/2321) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @fjod, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/EntityFramework.Docs/issues/2321. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
